[project]
name = "albatros"
version = "0.1.0"
description = ""
authors = []
dependencies = ["client"]
requires-python = "~=3.11"
dynamic = ["una"]          # needed for hatch-una metadata hook to work
[dependency-groups]
dev = []

[tool.uv.sources]

[tool.uv.sources.client]
workspace = true
[build-system]
requires = ["hatchling", "hatch-una"]
build-backend = "hatchling.build"

[tool.hatch.metadata]
allow-direct-references = true

[tool.hatch.build.hooks.una-build]
[tool.hatch.metadata.hooks.una-meta]
