name: unitycatalog

services:

  server:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - SSH_PRIVATE_KEY=/run/secrets/ssh_key
    ports:
      - "8080:8080"
    volumes:
      - type: bind
        source: ./etc/conf
        target: /opt/unitycatalog/etc/conf
      - type: bind
        source: ${SSH_KEY_PATH:-~/.ssh/id_rsa}
        target: /run/secrets/ssh_key
        read_only: true
      - type: volume
        source: unitycatalog_data
        target: /opt/unitycatalog/etc/data
  ui:
    build:
      context: ui/
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - server
      
volumes:
  # Persist docker volume across container restarts
  unitycatalog_data: